[package]
name = "build-info"
version = "0.0.5"
authors = ["Daniel Schemmel <daniel@schemmel.net>"]
edition = "2018"
publish = ["crates-io"]
repository = "https://github.com/danielschemmel/build-info/"
description = "Collects build-information of your Rust crate."
readme = "../README.md"
license = "MIT OR Apache-2.0"

[dependencies]
lazy_static = { version = "1", optional = true }
proc-macro-hack = "0.5"
proc-macro-nested = { version = "0.1", optional = true }
build-info-common = { version = "=0.0.3", path = "../build-info-common" }
build-info-proc = { version = "=0.0.5", path = "../build-info-proc" }

[features]
default = ["runtime"]
nested = ["proc-macro-nested"]
runtime = ["lazy_static", "build-info-proc/runtime"]
chrono = ["build-info-common/full-chrono"]
serde = ["build-info-common/enable-serde"]
