[package]
name = "build-info-proc"
version = "0.0.1-alpha.0"
authors = ["Daniel Schemmel <daniel@schemmel.net>"]
edition = "2018"
publish = ["crates-io"]

[lib]
proc-macro = true

[dependencies]
chrono = { version = "0.4", default_features = true }
format-buf = "1"
proc-macro2 = "1"
proc-macro-crate = "0.1"
proc-macro-hack = "0.5"
quote = "1"
serde_json = "1"
syn = "1"
build-info-common = { path = "../build-info-common" }

[features]
default = []
runtime = []
