[package]
name = "versionator-common"
version = "0.0.0"
authors = ["Daniel Schemmel <daniel.schemmel@comsys.rwth-aachen.de>"]
edition = "2018"
publish = false

[dependencies]
chrono = { version = "0.4", default-features = false }
derive_more = "0.99"
semver = "0.10"
serde = { version = "1", features = ["derive"], optional = true }

[features]
default = []
enable-serde = ["serde", "semver/serde", "chrono/serde"]
full-chrono = ["chrono/default"]
