[package]
name = "sample"
version = "0.0.9"
authors = ["Daniel Schemmel <daniel@schemmel.net>"]
edition = "2018"
publish = false
repository = "https://github.com/danielschemmel/build-info/"
description = "A sample program that uses the build-info crate."
readme = "../README.md"
license = "MIT OR Apache-2.0"

[dependencies]
build-info = { version = "=0.0.9", path = "../build-info" }

[build-dependencies]
build-info-build = { version = "=0.0.8", path = "../build-info-build" }
