[package]
name = "sample"
version = "0.0.2"
authors = ["Daniel Schemmel <daniel@schemmel.net>"]
edition = "2018"
publish = false
repository = "https://github.com/danielschemmel/build-info/"
description = "A sample program that uses the build-info crate."

[dependencies]
build-info = { version = "=0.0.2", path = "../build-info" }

[build-dependencies]
build-info-build = { version = "=0.0.2", path = "../build-info-build" }
