[package]
name = "sample"
version = "0.0.0"
authors = ["Daniel Schemmel <daniel.schemmel@comsys.rwth-aachen.de>"]
edition = "2018"

[dependencies]
versionator = { path = "../versionator" }

[build-dependencies]
versionator-build = { path = "../versionator-build" }
