[package]
name = "build-info-build"
version = "0.0.18"
authors = ["Daniel Schemmel <daniel@schemmel.net>"]
edition = "2018"
publish = ["crates-io"]
repository = "https://github.com/danielschemmel/build-info/"
description = "Provides the data consumed by the build-info crate. Use as a build-dependency."
readme = "../README.md"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1"
base64 = "0.12"
bincode = "1"
cargo_metadata = "0.10"
lazy_static = "1"
git2 = { version = "0.13", default-features = false, optional = true }
glob = "0.3"
pretty_assertions = "0.6"
rustc_version = "0.2"
serde_json = "1"
xz2 = "0.1"

build-info-common = { version = "=0.0.18", path = "../build-info-common", features = ["enable-serde"] }

[features]
default = ["dependencies", "git"]
dependencies = []
git = ["git2"]
