[package]
name = "build-info-build"
version = "0.0.17-alpha.1"
authors = ["Daniel Schemmel <daniel@schemmel.net>"]
edition = "2018"
publish = ["crates-io"]
repository = "https://github.com/danielschemmel/build-info/"
description = "Provides the data consumed by the build-info crate. Use as a build-dependency."
readme = "../README.md"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1"
git2 = { version = "0.13", default-features = false, optional = true }
glob = "0.3"
rustc_version = "0.2"
serde_json = "1"
toml = "0.5"

build-info-common = { version = "=0.0.17-alpha.1", path = "../build-info-common", features = ["enable-serde"] }

[features]
default = ["git"]
git = ["git2"]
