[package]
name = "build-info-build"
version = "0.0.2"
authors = ["Daniel Schemmel <daniel@schemmel.net>"]
edition = "2018"
publish = ["crates-io"]
repository = "https://github.com/danielschemmel/build-info/"

[dependencies]
anyhow = "1"
git2 = { version = "0.13", default-features = false }
glob = "0.3"
rustc_version = "0.2"
serde_json = "1"
toml = "0.5"
build-info = { version = "=0.0.2", path = "../build-info", features = ["serde"] }
